name: GitHub Actions Linting
on:
  push:
  pull_request:
    branches: [develop, master, merge-branch]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: format JS
        run: npm run format:js
      - name: lint JS
        run: npm run lint:js
      - name: format CSS
        run: npm run format:css
      - name: lint CSS
        run: npm run lint:css
